# ============
#  _config.yml
# ============

title: Bill Blog
SEOTitle: bill74186的博客 | Bill Blog
author: bill74186
header-img: img/home-bg.png
description: 「一“码”之缘，有“源”再见！」    ——bill74186
keyword: "Bill, Bill Blog, Bill的博客, bill71186, 比尔, HTML, blog"
url: "https://bill74186.github.io"
baseurl: ""
repo: "bill74186.github.io"

sidebar: true
sidebar-about-description: "目标决定你将成为什么样的人！"
sidebar-avatar: /img/bill74186.png
sidebar-qq: 3854052547
sidebar-wechat: mmll1920141
sidebar-email: bill74186@outlook.com

future: true

RSS: true
#weibo_username: bill74186
#jianshu_username: bill74186
zhihu_username: bill74186
github_username: bill74186
#twitter_username: bill74186
#facebook_username: Github-Bill
#linkedin_username: firstname-lastname-idxxxx

highlighter: rouge
permalink: pretty
paginate: 5
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
start_time: 2026
language: zh-CN
timezone: CN

plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

microsoft-clarity:
  enable: true
  clarity_id: x33wgbqrbr

google_analytics:
  enable: false
  ga_track_id: "UA-xxxxxx-xx"
  ga_domain: bill74186.github.io

baidu_tongji:
  enable: true
  ba_track_id: 788ec39160ac61840afc0489faf9298f

# Comments switch
comments: true

giscus:
  enable: true
  repo: "bill74186/bill74186.github.io"
  repo_id: "R_kgDOSuyHDQ"
  category: "Announcements"
  category_id: "DIC_kwDOSuyHDc4C-w2s"
  mapping: "pathname"
  strict: 0
  reactions_enabled: 1
  emit_metadata: 1
  input_position: "top"
  theme: "light"
  lang: "zh-CN"
  loading: "lazy"

utterances:
  enable: false
  repo: "bill74186/bill74186.github.io"
  issue_term: "pathname"
  label: "Comment"
  theme: "github-light"

gitalk:
  enable: false
  clientID: "Ov23liP2CLqcJYEBhES0"
  clientSecret: "dc0393f29a8165ce41468028b6f4ec16c3a42cf4"
  repo: "bill74186.github.io"
  owner: "bill74186"
  admin: "bill74186"
  distractionFreeMode: true

featured-tags: true
featured-condition-size: 1

chrome-tab-theme-color: "#000000"
service-worker: true
mathjax: true

friends: [
    { title: "AI Chat", href: "/AI-Chat/web/chat.html"},
    { title: "TACS", href: "https://github.com/TACS-Studio/"},
    { title: "bill74286", href: "http://github.com/bill74286/"},
    { title: "Github", href: "https://github.com/"},
    { title: "2048", href: "/2048-Game/"}
]
