# ============
#  _config.yml
# ============

title: Bill Blog
SEOTitle: bill74186的博客 | Bill Blog
header-img: img/post-bg-desk.jpg
email: bill74186@outlook.com
description: 「"一“码”之缘，有“源”再见！」    ——bill71186
keyword: "Bill, Bill Blog, Bill的博客, bill71186, 比尔, HTML, blog"
url: "https://bill74186.github.io"
baseurl: ""
github_repo: "https://github.com/bill74186/bill74186.github.io.git"

sidebar: true
sidebar-about-description: "目标决定你将成为什么样的人！"
sidebar-avatar: /img/bill74186.png

future: true

RSS: false
#weibo_username: bill74186
zhihu_username: bill74186
github_username: bill74186
#twitter_username: bill74186
#facebook_username:  bill74186
#linkedin_username:  firstname-lastname-idxxxx

highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
timezone: CN

plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Baidu Analytics
ba_track_id: 788ec39160ac61840afc0489faf9298f

# Google Analytics
# ga_track_id: "UA-xxxxxx-xx" # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

featured-tags: true
featured-condition-size: 1

chrome-tab-theme-color: "#000000"
service-worker: true
page-mathjax: false

friends: [
    { title: "TACS", href: "https://github.com/TACS-Studio/"},
    { title: "Install-Kali-NetHunter", href: "http://github.com/Install-Kali-NetHunter/"},
    { title: "Github", href: "https://github.com/"},
    { title: "2048", href: "https://bill74186.github.io/2048-Game/"}
]
